version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 128M